import React from 'react';
import { Sparkles, Wand2, Eye, Download, Smartphone, Layers } from 'lucide-react';

export const FeaturesSection: React.FC = () => {
  const features = [
    {
      icon: <Sparkles className="w-6 h-6 text-blue-400" />,
      title: 'AI Website Generation',
      description: 'Generate complete multi-file HTML, CSS, and JS web applications from a single natural-language description.',
      tag: 'Core Feature',
    },
    {
      icon: <Wand2 className="w-6 h-6 text-purple-400" />,
      title: 'AI Editing & Refinement',
      description: 'Tell VERVOX what you want to change — "make the hero section bigger", "change color theme", or "add testimonials".',
      tag: 'Natural Language',
    },
    {
      icon: <Eye className="w-6 h-6 text-emerald-400" />,
      title: 'Real-Time Live Preview',
      description: 'See instant live previews of your generated website in real-time as you chat with AI or manually edit code.',
      tag: 'Instant Render',
    },
    {
      icon: <Download className="w-6 h-6 text-indigo-400" />,
      title: 'Full ZIP Export',
      description: 'Download your complete website workspace as a standalone ZIP archive with clean code and setup instructions.',
      tag: 'Zero Lock-in',
    },
    {
      icon: <Smartphone className="w-6 h-6 text-pink-400" />,
      title: 'Responsive Across Devices',
      description: 'Websites generated by VERVOX are built mobile-first and tested for smooth layout scaling on Desktop, Tablet & Mobile.',
      tag: 'All Screens',
    },
    {
      icon: <Layers className="w-6 h-6 text-amber-400" />,
      title: 'Modular Template Gallery',
      description: 'Choose from 8+ professionally designed starter templates for portfolios, gaming portals, SaaS, restaurants, and blogs.',
      tag: 'Kickstart',
    },
  ];

  return (
    <section id="features" className="py-24 bg-slate-950 border-t border-slate-900 relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-block px-3 py-1 rounded-full bg-indigo-500/10 text-indigo-400 text-xs font-mono font-bold uppercase tracking-wider mb-3">
            Why Choose VERVOX
          </div>
          <h2 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight">
            Everything You Need to Build Websites at Light Speed
          </h2>
          <p className="text-slate-400 text-base sm:text-lg mt-4">
            Engineered for developers, creators, and entrepreneurs who want high-performance websites without manual coding friction.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((f, i) => (
            <div
              key={i}
              className="p-8 rounded-2xl bg-slate-900/60 border border-slate-800 hover:border-indigo-500/40 transition-all duration-300 hover:-translate-y-1 group backdrop-blur-sm flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-6">
                  <div className="w-12 h-12 rounded-xl bg-slate-800 border border-slate-700/60 flex items-center justify-center group-hover:scale-110 transition-transform">
                    {f.icon}
                  </div>
                  <span className="text-[10px] font-mono uppercase font-bold text-slate-400 px-2.5 py-1 rounded-full bg-slate-800/80 border border-slate-700/50">
                    {f.tag}
                  </span>
                </div>
                <h3 className="text-xl font-bold text-white mb-2">{f.title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed">{f.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};
